// Disease labels mirrored from data/illnesses.sqlite3 for ID-only callers.
export const DISEASE_NAMES: Record<number, string> = {
  "1": "hypertensive disease",
  "2": "diabetes",
  "3": "depression mental",
  "4": "coronary arteriosclerosis",
  "5": "pneumonia",
  "6": "failure heart congestive",
  "7": "accident cerebrovascular",
  "8": "asthma",
  "9": "myocardial infarction",
  "10": "hypercholesterolemia",
  "11": "infection",
  "12": "infection urinary tract",
  "13": "anemia",
  "14": "chronic obstructive airway disease",
  "15": "dementia",
  "16": "insufficiency renal",
  "17": "confusion",
  "18": "degenerative polyarthritis",
  "19": "hypothyroidism",
  "20": "anxiety state",
  "21": "malignant neoplasms",
  "22": "acquired immuno-deficiency syndrome",
  "23": "cellulitis",
  "24": "gastroesophageal reflux disease",
  "25": "septicemia",
  "26": "deep vein thrombosis",
  "27": "dehydration",
  "28": "neoplasm",
  "29": "embolism pulmonary",
  "30": "epilepsy",
  "31": "cardiomyopathy",
  "32": "chronic kidney failure",
  "33": "carcinoma",
  "34": "hepatitis C",
  "35": "peripheral vascular disease",
  "36": "psychotic disorder",
  "37": "hyperlipidemia",
  "38": "bipolar disorder",
  "39": "obesity",
  "40": "ischemia",
  "41": "cirrhosis",
  "42": "exanthema",
  "43": "benign prostatic hypertrophy",
  "44": "kidney failure acute",
  "45": "mitral valve insufficiency",
  "46": "arthritis",
  "47": "bronchitis",
  "48": "hemiparesis",
  "49": "osteoporosis",
  "50": "transient ischemic attack",
  "51": "adenocarcinoma",
  "52": "paranoia",
  "53": "pancreatitis",
  "54": "incontinence",
  "55": "paroxysmal dyspnea",
  "56": "hernia",
  "57": "malignant neoplasm of prostate",
  "58": "edema pulmonary",
  "59": "lymphatic diseases",
  "60": "stenosis aortic valve",
  "61": "malignant neoplasm of breast",
  "62": "schizophrenia",
  "63": "diverticulitis",
  "64": "overload fluid",
  "65": "ulcer peptic",
  "66": "osteomyelitis",
  "67": "gastritis",
  "68": "bacteremia",
  "69": "failure kidney",
  "70": "sickle cell anemia",
  "71": "failure heart",
  "72": "upper respiratory infection",
  "73": "hepatitis",
  "74": "hypertension pulmonary",
  "75": "deglutition disorder",
  "76": "gout",
  "77": "thrombocytopaenia",
  "78": "hypoglycemia",
  "79": "pneumonia aspiration",
  "80": "colitis",
  "81": "diverticulosis",
  "82": "suicide attempt",
  "83": "Pneumocystis carinii pneumonia",
  "84": "hepatitis B",
  "85": "parkinson disease",
  "86": "lymphoma",
  "87": "hyperglycemia",
  "88": "encephalopathy",
  "89": "tricuspid valve insufficiency",
  "90": "Alzheimer's disease",
  "91": "candidiasis",
  "92": "neuropathy",
  "93": "kidney disease",
  "94": "fibroid tumor",
  "95": "glaucoma",
  "96": "neoplasm metastasis",
  "97": "malignant tumor of colon",
  "98": "ketoacidosis diabetic",
  "99": "tonic-clonic epilepsy",
  "100": "malignant neoplasms",
  "101": "respiratory failure",
  "102": "melanoma",
  "103": "gastroenteritis",
  "104": "malignant neoplasm of lung",
  "105": "manic disorder",
  "106": "personality disorder",
  "107": "primary carcinoma of the liver cells",
  "108": "emphysema pulmonary",
  "109": "hemorrhoids",
  "110": "spasm bronchial",
  "111": "aphasia",
  "112": "obesity morbid",
  "113": "pyelonephritis",
  "114": "endocarditis",
  "115": "effusion pericardial",
  "116": "chronic alcoholic intoxication",
  "117": "pneumothorax",
  "118": "delirium",
  "119": "neutropenia",
  "120": "hyperbilirubinemia",
  "121": "influenza",
  "122": "dependence",
  "123": "thrombus",
  "124": "cholecystitis",
  "125": "hernia hiatal",
  "126": "migraine disorders",
  "127": "pancytopenia",
  "128": "cholelithiasis",
  "129": "tachycardia sinus",
  "130": "ileus",
  "131": "adhesion",
  "132": "delusion",
  "133": "affect labile",
  "134": "decubitus ulcer"
};
